### ISSUE TITLE
3D model assembly file with all the parts together

### ISSUE THREAD

**Issue by Arakistech** [AndreaFavero71/cubotino#10]
Could you please add a 3D model assembly file with all the parts together?

Thanks

**Comment by AndreaFavero71** [comment]
Hi, the complete assy in step format is now available at: https://github.com/AndreaFavero71/cubotino/blob/main/stp/CUBOTino_Autonomous_rev8_step.zip
In the assy there also are some of the alternative parts and components.
I assume parts name are self explanatory.
Regards.
Andrea

**Comment by AndreaFavero71** [comment]
Uploaded assy
