### ISSUE TITLE
Errors in RPi setup

### ISSUE THREAD

**Issue by MasterMD** [AndreaFavero71/cubotino#11]
Hi!
Great project !!
During the execution of the setup.sh I got an error :
![image](https://github.com/AndreaFavero71/cubotino/assets/43536204/3a59d02c-0276-48ba-9887-12346be5302b)
but the procedure continues.
But at about 47% of the unpacking it stops with this error:
![image](https://github.com/AndreaFavero71/cubotino/assets/43536204/478636c6-2660-46e2-b54f-2e1d75b92909)
I repeated the whole procedure (from writing new image on the SD card), but same result.
What to do?

kind regards,
Maarten

**Comment by AndreaFavero71** [comment]
Hi, I'm going to be holiday for one more week and I'm not equipped to run any test.
In case there are recent changes on libraries, blocking the installation, there is little I can do shortly.

What I can do now, is to double check with you if any error at your side.
On 15th July 2023 the installation process was working fine: If you share your email address I'll send you the printout log I've saved (and downloaded from my NAS).
Are you sure the flashed OS is the "Raspberry Pi OS (Legacy)”, not the default one proposed by the Raspberry Pi Imager?
If the chosen OS is correct, which Raspberry Pi board are you using?

Kind regards
Andrea

**Comment by MasterMD** [comment]
Hi Andrea,

Thanks for your response!

After my experience with the RPi installation part, I was a little confused what to do.
(burning the image and verifying had been succesfull)

A few days later I decided to try it again with a different SD card, and ... the procedure finished succesfull !!
Sorry, that I didn't update my GitHub thread yet ...

I went on with the assembly, and 'discovered' that my camera extension flat cable was of a wrong type
(some years ago I build a cube resolver with RPi 3 and Technic Lego construction, so I thought I have a camera and cable ;-)
but I wasn't aware that the Zero has a different connection).

I ordered a new cable, and started testing. Unfortunately the camera didn't function (at all).
The connection at the Pi Zero appears to be rather fragile, but after re-arranging the camera still doesn't work.
Now I am awaiting a new camera board; hopely I can proceed then.

I admire the way you have set-up this whole project: the lovely design, and surely the extended documentation.
I found some details to (maybe) improve. I you like it, I will send them as soon as I have my Cubotino operating.

Thanks again !




Kind regards,
Maarten

**Comment by AndreaFavero71** [comment]
Hi Maarten, very good you found the solution for the setup issue.
I'll close this thread with a comment about microSD and possible setup
errors, and I'll add it to the troubleshooting chapter.

I received once a bad camera cable: At the CSI connector extremity, the
insulation was too large at one side (and narrow al the opposite side)
preventing the traces alignment (connection) to the CSI connector.
I did cut away a narrow strip of insulation, and inserted the cable forced
to that side: That arrangement is still working after one year, including a
few reopening of it.

I'm always open for corrections and improvements; Please collect and share
them via email, to ***@***.***, once you'll have your bot up
and running.

Kind regards
Andrea

Il dom 6 ago 2023, 12:16 MasterMD ***@***.***> ha scritto:

**Comment by AndreaFavero71** [comment]
In case of Errors in Rpi setup, try with a different microSD as it might be the source of the problem
