### ISSUE TITLE
CPL file for JLCPCB board assembly

### ISSUE THREAD

**Issue by KH6JAG** [AndreaFavero71/cubotino#12]
Is there a CPL file available to request a quote from JLCPCB for board and assembly?
The link given in connections_board/info/ is only for the board.

When chatting with JLCPCB today, I was advised that I need to either provide the CPL file or do a complete design using EadyEDA.
The Gerber files imported without error to do a board order, but they cannot be imported into Easy EDA.

I've also asked PCBWAY for a quote on the assembled board - they usually respond in 2-3 days with a quote for assembled boards.

Thanks for all your Cubotino project efforts!

**Comment by AndreaFavero71** [comment]
Hi, I just googled what CPL file is meant for, and it looks like it includes the BOM (all compoents), as per the issue title you have raised :-)
I'm afraid I don't have the CPL file, the board has been drawn by another Maker and the files I received are those that are published.
I hope you'll take a big breath, and decide to order/solder the components by yourself...
Regards, Andrea

**Comment by KH6JAG** [comment]
Thanks for the reply.  I think I can build the CPL file from the info provided by the board maker on the PCBWAY share site.The JLCPCB site offered a potential lower cost source of supplyI have already have soldered a breadboard unit from the Instructable.The newer build is to support a group of youngsters so they wouldn’t need to solder as in requires SMD and just do a mechanical build.Thanks again,  Jim Sent from Mail for Windows From: AndreaSent: Monday, November 6, 2023 1:37 PMTo: AndreaFavero71/cubotinoCc: KH6JAG; AuthorSubject: Re: [AndreaFavero71/cubotino] CPL file for JLCPCB board assembly (Issue #12) Hi, I just googled what CPL file is meant for, and it looks like it includes the BOM (all compoents), as per the issue title you have raised :-)I'm afraid I don't have the CPL file, the board has been drawn by another Maker and the files I received are those that are published.I hope you'll take a big breath, and decide to order/solder the components by yourself...Regards, Andrea—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by AndreaFavero71** [comment]
Hi Jim,
I've the feeling you are referring to the the board designed by G2G, as you're mentioning smd components.
This board, despite having some positive aspects, is not supported by me and not described in the instructions. In my opinion, this board increases complexity by adding extra connectors (i.e on the display) and smd components.
If you prefer this board, as it comes fully assembled, please note you'll have to use specific connectors at the servos, led module,  touch sensor and display: For reference, please check the "I MADE IT" made by g2maurer at Instructables (https://www.instructables.com/CUBOTino-Autonomous-Small-3D-Printed-Rubiks-Cube-R/#discuss).
g2maurer has posted the email in case there are maker interested on getting that board: Please check the chat at Instructables page for his/her email address.
You'll also notice the display is screwed directly to the PCB_cover, therefore you'll better ask g2maurer for the stl file.


For the supported board (V1.6) the gerber files are saved at /gerber folder on this project; This board is "just" essential, no BOM saved at the boards manufacturer, yet it only uses little through hole components.
This board is the one described in the instructions.

I'm ok with both option, yet it's important you're aware about the differences.
I hope you and the youngsters will have fun with the project.
Regards, Andrea

**Comment by AndreaFavero71** [comment]
This issue relates to a board version that isn't supported by Andrea Favero, board not covered in the instructions.
The supported board (V1.6) doesn't have smd components, neither the CPL file yet is is simple to solder at home.

**Comment by KH6JAG** [comment]
Thank you for the reply.  We have a project that is building as many of the Rubik's robots that have good documentation.  Cubotino has one of the best documentation sets.  I was able to get a build quote for the boards that required the CPL file.  I'll send you an update once the units are built with these boards.
