### ISSUE TITLE
Display test not working and install doesnt work properly.

### ISSUE THREAD

**Issue by varkanoid** [AndreaFavero71/cubotino#15]
Hi,

I decided to change my microsd card before I ran through the setup process and tuning. I also saw you had updated recently so I thought I will refresh the whole thing. I had only done a few things before like test the display was working with your test script which it was. I started from scratch and imaged the new micro sd. I then cloned your repository and followed your install instructions.

Issue 1 was when you click y to restart, you get no GUI after the restart. I had to enable it myself with raspi-config.
Issue 2 now when I run the display test I get these errors below. This is strange because with the previous install it worked fine.

(.virtualenvs) pi@cubotino:~/cubotino/src $ python Cubotino_T_display.py
Activated pigpiod
Error on converting imported parameters to int
Display test for 20 seconds
Display shows rectangles, text and Cubotino logo
Traceback (most recent call last):
  File "/home/pi/cubotino/src/Cubotino_T_display.py", line 298, in <module>
    display.test1_display()
  File "/home/pi/cubotino/src/Cubotino_T_display.py", line 217, in test1_display
    w = self.disp_w                                            # display width, retrieved by display setting
AttributeError: 'Display' object has no attribute 'disp_w'

So I am using the one dated 22nd January 2024.

Any ideas ?

**Comment by varkanoid** [comment]
Also getting this error when I try to run the Tuning GUI.
(.virtualenvs) pi@cubotino:~/cubotino/src $ python Cubotino_T_servos_GUI.py

Activated pigpiod
Error on converting imported parameters to int
Traceback (most recent call last):
  File "/home/pi/cubotino/src/Cubotino_T_servos_GUI.py", line 30, in <module>
    import Cubotino_T_servos as servo    # custom library controlling Cubotino servos and led module
  File "/home/pi/cubotino/src/Cubotino_T_servos.py", line 37, in <module>
    s_disp.set_backlight(0)     # display backlight is set off
  File "/home/pi/cubotino/src/Cubotino_T_display.py", line 85, in set_backlight
    self.disp.set_backlight(value)
AttributeError: 'Display' object has no attribute 'disp'

**Comment by varkanoid** [comment]
Seems some kind of issue with setting the display ? 

(.virtualenvs) pi@cubotino:~/cubotino/src $ python Cubotino_T_servos.py -set 0

Activated pigpiod
Error on converting imported parameters to int
Traceback (most recent call last):
  File "/home/pi/cubotino/src/Cubotino_T_servos.py", line 37, in <module>
    s_disp.set_backlight(0)     # display backlight is set off
  File "/home/pi/cubotino/src/Cubotino_T_display.py", line 85, in set_backlight
    self.disp.set_backlight(value)
AttributeError: 'Display' object has no attribute 'disp'

**Comment by AndreaFavero71** [comment]
Hi varkanoid,
you are right, I copied the wrong Cubotino_T_settings.txt file.
The settings from this file are uploaded by different scripts.
I have set a system from flashing the image onward: It looks ok now.

Edit:
The .txt files don't get downloaded by "git pull", so you have to download the file an copy into the /src folder,
or just edit Cubotino_T_settings.txt and 

1) add a comma after "vnc_delay": "0.0" 
2) add:
    "built_by": "",
    "built_by_x": "25",
    "built_by_fs": "16"

Edit2:
1) delete  Cubotino_T_settings.txt
2) git reset --hard"
This downloads the latest .txt file :-)

Please feedback if it works at your end too.
Regards, Andrea

**Comment by varkanoid** [comment]
Works again now than you very much it is appreciated. :)

Just a small thing you left the displ width at 130 instead of the default 128. I know you changed it to 130 for your screen but it works fine with 128 with my screen. Just a minor thing you should be aware of.

**Comment by AndreaFavero71** [comment]
Hi, thank you for the note ... just checked that 130 is into the file and instruction since June 2022. I'm going to correct the file now, and the instruction for the next revision.
Wrt the 1st issue you pointed out, after the installation, the Desktop environment can be activated by editing crontab: This is the way I've indicated in the instructions, dor sure there are other ways.
I'm going to close this Issue.
Enjoy the project, Andrea
