### ISSUE TITLE
Error when Cubotino_T_coordinates.txt is missing (or empty)

### ISSUE THREAD

**Issue by varkanoid** [AndreaFavero71/cubotino#16]
Hi,

sorry found another issue.

I have done my tuning succesfully. Came to start the solver and it errors below

<img width="347" alt="image" src="https://github.com/AndreaFavero71/cubotino/assets/16356424/c2139c3f-83e2-4403-94f7-0c56a04c69db">

**Comment by varkanoid** [comment]
Seems to be this bit in the file it fails on as the .txt file doesnt exist it doesnt define the lines parameter.
<img width="538" alt="image" src="https://github.com/AndreaFavero71/cubotino/assets/16356424/82a41d90-3cd6-4f69-a4e8-41a5995749c5">

**Comment by varkanoid** [comment]
So I added a blank Cubotino_T_coordinates.txt file and it passed that section without an error.
However I now get this error. So not sure whether this is because I created a blank coord file.
<img width="368" alt="image" src="https://github.com/AndreaFavero71/cubotino/assets/16356424/b8e18ecc-34b9-475f-ad1f-23f04d6a22e8">

**Comment by AndreaFavero71** [comment]
Hi Varkanoid, you're right again.
Released an improved version.
Regards, Andrea

**Comment by varkanoid** [comment]
Thanks its working now.

**Comment by varkanoid** [comment]
Working once again great job. Solved my first cube :)
