### ISSUE TITLE
servos_setting_GUI.py file is required?

### ISSUE THREAD

**Issue by AgnesBarta** [AndreaFavero71/cubotino#21]
Hi, 

This project sounds really great, we are trying to bring up the source code. We have some issue to init the GUI to do the fine tuning setup. When we are running Cubotino_T_servos_GUI.py it is expecting DISPLAY env variable to be set what is not the case for us. In the latest documentation we see to bring up the GUI with servos_setting_GUI.py but that one I am not able to see in the repo. Could you please help us if we miss something? Thank you so much.

**Comment by AndreaFavero71** [comment]
Hi, the GUI file is named Cubotino_T_servos_GUI.py and it requires the virtual environment.
Anyhow, please be informed that today I have released a rather large update (V7.0), involving 7 python files and 2 text files.
Please check, and report, the version of the Cubotino_T.py (add the argument -v , again after activating the virtual enviroment) that gives you the problem.

**Comment by AgnesBarta** [comment]
Thank you for confirming. Finally we got the issue resolved and were able to bring the GUI app. Thank you for the quick answer.

**Comment by AndreaFavero71** [comment]
Very good. Still applies that I have released an update today, and you might benefit from starting with it.
If of your interest, below the necessary command:
```
git reset --hard origin/main
git pull
```
