### ISSUE TITLE
Save new servo settings from GUI just saves old values

### ISSUE THREAD

**Issue by paul-1** [AndreaFavero71/cubotino#22]
Looks like you left in test code.  Removing the for loop, and uncommenting the lines takes care of it.

https://github.com/AndreaFavero71/cubotino/blob/9859548dd501dde5bdbb7e18a4b810a7e3961cb8/src/Cubotino_T_servos_GUI.py#L191

**Comment by AndreaFavero71** [comment]
You're fully right, thank you for notifying.
