### ISSUE TITLE
Schematic for the PCB

### ISSUE THREAD

**Issue by belenhed** [AndreaFavero71/cubotino#8]
Hello can we have the schematic for the PCB so maybe we can make one at home with a CNC?
Thanks

**Comment by AndreaFavero71** [comment]
This answer is absolutely late.....anyhow:
https://github.com/AndreaFavero71/cubotino/blob/main/connections_board/info/Schematic_Cubotino.pdf

**Comment by AndreaFavero71** [comment]
Schematic is finally loaded
